package com.sarrawi.mytranslate.util

object LanguageCodes {
    val languages = mapOf(
        "af" to "Afrikaans",
        "sq" to "Albanian",
        "ar" to "Arabic",
        "hy" to "Armenian",
        "bn" to "Bengali",
        "bs" to "Bosnian",
        "ca" to "Catalan",
        "hr" to "Croatian",
        "cs" to "Czech",
        "da" to "Danish",
        "nl" to "Dutch",
        "en" to "English",
        "eo" to "Esperanto",
        "et" to "Estonian",
        "tl" to "Filipino",
        "fi" to "Finnish",
        "fr" to "French",
        "de" to "German",
        "el" to "Greek",
        "gu" to "Gujarati",
        "hi" to "Hindi",
        "hu" to "Hungarian",
        "is" to "Icelandic",
        "id" to "Indonesian",
        "it" to "Italian",
        "ja" to "Japanese",
        "jw" to "Javanese",
        "ko" to "Korean",
        "la" to "Latin",
        "lt" to "Lithuanian",
        "mk" to "Macedonian",
        "ml" to "Malayalam",
        "mr" to "Marathi",
        "ne" to "Nepali",
        "pl" to "Polish",
        "pt" to "Portuguese",
        "pa" to "Punjabi",
        "ro" to "Romanian",
        "ru" to "Russian",
        "sr" to "Serbian",
        "si" to "Sinhalese",
        "es" to "Spanish",
        "su" to "Sundanese",
        "sw" to "Swahili",
        "sv" to "Swedish",
        "ta" to "Tamil",
        "te" to "Telugu",
        "th" to "Thai",
        "tr" to "Turkish",
        "uk" to "Ukrainian",
        "vi" to "Vietnamese",
        "cy" to "Welsh",
        "yi" to "Yiddish",
        "zh" to "Chinese",
        "ka" to "Georgian",
        "am" to "Amharic",
        "ht" to "Haitian Creole",
        "he" to "Hebrew",
        "no" to "Norwegian",
        "uz" to "Uzbek",
        "my" to "Burmese",
        "zu" to "Zulu"
    )


    val map = mapOf(
        "العربية" to "ar",
        "الإنجليزية" to "en",
        "الفرنسية" to "fr",
        "الإسبانية" to "es"
    )
}
